In [ ]:
import pandas as pd

# 新段落

In [ ]:
url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv"
df = pd.read_csv(url,index_col=0)
df.head()

iso2 iso3  code3    FIPS   Admin2 Province_State Country_Region  \
UID                                                                        
84001001   US  USA    840  1001.0  Autauga        Alabama             US   
84001003   US  USA    840  1003.0  Baldwin        Alabama             US   
84001005   US  USA    840  1005.0  Barbour        Alabama             US   
84001007   US  USA    840  1007.0     Bibb        Alabama             US   
84001009   US  USA    840  1009.0   Blount        Alabama             US   

                Lat      Long_          Combined_Key  ...  12/5/22  12/6/22  \
UID                                                   ...                     
84001001  32.539527 -86.644082  Autauga, Alabama, US  ...      230      230   
84001003  30.727750 -87.722071  Baldwin, Alabama, US  ...      716      716   
84001005  31.868263 -85.387129  Barbour, Alabama, US  ...      103      103   
84001007  32.996421 -87.125115     Bibb, Alabama, US  ...      108      108   
84001009  33.982109 -86.567906   Blount, Alabama, US  ...      259      259   

          12/7/22  12/8/22  12/9/22  12/10/22  12/11/22  12/12/22  12/13/22  \
UID                                                                           
84001001      230      230      230       230       230       230       230   
84001003      717      717      717       717       717       717       717   
84001005      103      103      103       103       103       103       103   
84001007      108      108      108       108       108       108       108   
84001009      260      260      260       260       260       260       260   

          12/14/22  
UID                 
84001001       230  
84001003       717  
84001005       103  
84001007       108  
84001009       260  

[5 rows x 1069 columns]

In [ ]:
death_by_state = df.groupby('Province_State')[df.columns[11:]].sum()
death_by_state.head(10)

1/22/20  1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  \
Province_State                                                           
Alabama                 0        0        0        0        0        0   
Alaska                  0        0        0        0        0        0   
American Samoa          0        0        0        0        0        0   
Arizona                 0        0        0        0        0        0   
Arkansas                0        0        0        0        0        0   
California              0        0        0        0        0        0   
Colorado                0        0        0        0        0        0   
Connecticut             0        0        0        0        0        0   
Delaware                0        0        0        0        0        0   
Diamond Princess        0        0        0        0        0        0   

                  1/28/20  1/29/20  1/30/20  1/31/20  ...  12/5/22  12/6/22  \
Province_State                                        ...                     
Alabama                 0        0        0        0  ...    20652    20652   
Alaska                  0        0        0        0  ...     1436     1436   
American Samoa          0        0        0        0  ...       34       34   
Arizona                 0        0        0        0  ...    31751    31751   
Arkansas                0        0        0        0  ...    12585    12594   
California              0        0        0        0  ...    97645    97655   
Colorado                0        0        0        0  ...    13652    13668   
Connecticut             0        0        0        0  ...    11587    11602   
Delaware                0        0        0        0  ...     3172     3172   
Diamond Princess        0        0        0        0  ...        0        0   

                  12/7/22  12/8/22  12/9/22  12/10/22  12/11/22  12/12/22  \
Province_State                                                              
Alabama             20682    20682    20682     20682     20682     20682   
Alaska               1436     1436     1436      1436      1436      1436   
American Samoa         34       34       34        34        34        34   
Arizona             31822    31822    31822     31822     31822     31822   
Arkansas            12603    12613    12623     12631     12631     12631   
California          97682    97817    97834     97834     97834     97873   
Colorado            13682    13697    13704     13704     13704     13715   
Connecticut         11603    11603    11603     11603     11603     11603   
Delaware             3172     3172     3184      3184      3184      3184   
Diamond Princess        0        0        0         0         0         0   

                  12/13/22  12/14/22  
Province_State                        
Alabama              20682     20704  
Alaska                1436      1436  
American Samoa          34        34  
Arizona              31822     31929  
Arkansas             12638     12647  
California           97892     97918  
Colorado             13740     13743  
Connecticut          11656     11659  
Delaware              3184      3185  
Diamond Princess         0         0  

[10 rows x 1058 columns]

In [ ]:
test = pd.DataFrame(death_by_state.iloc[1])
current_state = test.columns[0]
current_state
##### WARNING: is the data already counting cumulative or is it daily cases?
test.columns=['cum_death']
test['new_death']=test['cum_death'].diff().fillna(test['cum_death'])
#print(df)
#test.reset_index()
#test.head()

In [ ]:
from math import exp
def model(params, time_step):
  p,q,m = params
  N=[]
  for t in range(1,time_step):
    current=m*(1-exp(-(p+q)*t))/(1+(q/p)*exp(-(p+q)*t))
    last=m*(1-exp(-(p+q)*(t-1)))/(1+(q/p)*exp(-(p+q)*(t-1)))
    N.append(current-last)
  return N


def error(params, time_step, actual_N):
  pred_N = model(params,time_step)
  N_error = []
  for t in range(0,time_step-1):
    N_error.append((actual_N[t+1]-pred_N[t])**2)
  total_error = sum(N_error)
  return total_error




In [ ]:
import numpy as np
from scipy.optimize import minimize
import pandas as pd

In [ ]:
initial_value = [0.027,0.003,0.03]
bnds = [(0, None), (0, None), (0, None)]
res = minimize(error,initial_value, args = (1028,test.new_death), bounds = bnds, tol=1e-8, method = 'Powell')

In [ ]:
print(res)

   direc: array([[-1.20012006e-05,  7.47837393e-04,  9.60104503e+01],
       [-3.04291749e-05,  1.12323411e-03, -1.39193406e+02],
       [-4.78326155e-06,  5.60700835e-04, -6.38933555e+01]])
     fun: 28422.787858961932
 message: 'Optimization terminated successfully.'
    nfev: 1198
     nit: 16
  status: 0
 success: True
       x: array([1.08686633e-04, 6.25513198e-03, 1.75989179e+03])


In [ ]:
def prediction(params,current_time, time_range):
  p,q,m = params
  N_t = []
  for t in range(current_time,current_time+time_range):
    current=m*(1-exp(-(p+q)*t))/(1+(q/p)*exp(-(p+q)*t))
    last=m*(1-exp(-(p+q)*(t-1)))/(1+(q/p)*exp(-(p+q)*(t-1)))
    N_t.append(current-last)
  return N_t




In [ ]:
len(death_by_state)

58

In [ ]:
final_prediction_df = pd.DataFrame()
for state in range(0,58):
  test = pd.DataFrame(death_by_state.iloc[state])
  current_state = test.columns[0]
  ##### WARNING: is the data already counting cumulative or is it daily cases?
  test.columns=['cum_death']
  test['new_death']=test['cum_death'].diff().fillna(test['cum_death'])
  initial_value = [0.027,0.03,100]
  bnds = [(0, None), (0, None), (10, None)]
  res = minimize(error,initial_value, args = (1028,test.new_death), bounds = bnds, tol=1e-8, method = 'Powell')
  print(res.x)
  final_prediction_df[current_state] = prediction(res.x,1018,400)


[6.85348468e-05 7.45512874e-02 7.15048376e+02]
[1.95890521e-06 1.32754303e-02 1.19923394e+03]
[4.74359040e-05 5.64467686e-03 6.25494210e+01]
[4.93288970e-04 4.34575555e-03 3.43540333e+04]
[1.73888509e-04 1.01622182e-01 4.71895508e+01]
[4.80542406e-06 2.29601548e-02 6.39887423e+04]
[2.93835533e-03 2.68151079e-02 2.15148859e+03]
[2.12348097e-03 2.85751395e-02 5.42844123e+03]
[1.71509248e-03 2.69908748e-02 7.61501051e+02]
[1.51278758e-17 5.02591791e-09 1.00000000e+01]
[1.68958999e-03 2.78090743e-02 7.32408180e+02]
[3.35690801e-04 4.69983359e-03 9.05015233e+04]
[1.42838592e-07 1.85237122e-02 2.36354418e+03]
[3.96790131e-04 1.58056185e-04 1.00000001e+01]
[4.40574432e-05 2.41494897e-02 1.48842242e+02]
[9.3192310e-05 6.1712102e-03 1.8597482e+03]
[1.92092126e-06 1.32804060e-01 7.47200918e+01]
[7.80890927e-04 3.61002049e-03 4.25513219e+04]
[4.18929984e-03 1.95916011e-10 1.03148714e+04]
[1.23673804e-05 2.25354100e-02 5.94767682e+03]
[1.87986134e-05 2.06375733e-02 5.80223146e+03]
[1.23394774e-05 

In [ ]:
final_prediction_df

Alabama    Alaska  American Samoa    Arizona  Arkansas  California  \
0       0.0  0.143865        0.070176  10.473993       0.0    0.000499   
1       0.0  0.142002        0.069990  10.429493       0.0    0.000488   
2       0.0  0.140162        0.069803  10.385155       0.0    0.000477   
3       0.0  0.138346        0.069615  10.340978       0.0    0.000466   
4       0.0  0.136553        0.069427  10.296961       0.0    0.000456   
5       0.0  0.134783        0.069239  10.253106       0.0    0.000445   
6       0.0  0.133035        0.069050  10.209411       0.0    0.000435   
7       0.0  0.131309        0.068861  10.165876       0.0    0.000425   
8       0.0  0.129606        0.068672  10.122500       0.0    0.000416   
9       0.0  0.127924        0.068482  10.079284       0.0    0.000406   
10      0.0  0.126264        0.068292  10.036226       0.0    0.000397   
11      0.0  0.124625        0.068102   9.993327       0.0    0.000388   
12      0.0  0.123007        0.067912   9.950587       0.0    0.000379   
13      0.0  0.121409        0.067721   9.908004       0.0    0.000370   
14      0.0  0.119832        0.067530   9.865579       0.0    0.000362   
15      0.0  0.118275        0.067338   9.823311       0.0    0.000354   
16      0.0  0.116738        0.067147   9.781199       0.0    0.000346   
17      0.0  0.115221        0.066955   9.739244       0.0    0.000338   
18      0.0  0.113723        0.066762   9.697445       0.0    0.000330   
19      0.0  0.112244        0.066570   9.655802       0.0    0.000323   
20      0.0  0.110785        0.066377   9.614314       0.0    0.000315   
21      0.0  0.109344        0.066184   9.572982       0.0    0.000308   
22      0.0  0.107921        0.065991   9.531803       0.0    0.000301   
23      0.0  0.106517        0.065798   9.490779       0.0    0.000294   
24      0.0  0.105131        0.065604   9.449909       0.0    0.000288   
25      0.0  0.103762        0.065410   9.409192       0.0    0.000281   
26      0.0  0.102411        0.065216   9.368629       0.0    0.000275   
27      0.0  0.101078        0.065022   9.328218       0.0    0.000269   
28      0.0  0.099761        0.064828   9.287960       0.0    0.000263   
29      0.0  0.098462        0.064633   9.247854       0.0    0.000257   

        Colorado   Connecticut      Delaware  Diamond Princess  ...  \
0   4.592948e-11  6.457412e-11  7.548806e-11      1.512795e-16  ...   
1   4.501999e-11  6.366463e-11  7.332801e-11      1.512795e-16  ...   
2   4.320100e-11  6.275513e-11  7.150902e-11      1.512795e-16  ...   
3   4.229150e-11  5.911716e-11  6.923528e-11      1.512795e-16  ...   
4   4.138201e-11  5.820766e-11  6.730261e-11      1.512795e-16  ...   
5   3.956302e-11  5.547918e-11  6.548362e-11      1.512795e-16  ...   
6   3.819878e-11  5.456968e-11  6.366463e-11      1.512795e-16  ...   
7   3.774403e-11  5.275069e-11  6.173195e-11      1.512795e-16  ...   
8   3.592504e-11  5.184120e-11  6.002665e-11      1.512795e-16  ...   
9   3.547029e-11  5.002221e-11  5.843503e-11      1.512795e-16  ...   
10  3.456080e-11  4.820322e-11  5.672973e-11      1.512795e-16  ...   
11  3.274181e-11  4.547474e-11  5.525180e-11      1.512795e-16  ...   
12  3.228706e-11  4.547474e-11  5.354650e-11      1.512795e-16  ...   
13  3.137757e-11  4.456524e-11  5.195488e-11      1.512795e-16  ...   
14  3.046807e-11  4.183676e-11  5.059064e-11      1.512795e-16  ...   
15  2.955858e-11  4.183676e-11  4.911271e-11      1.512795e-16  ...   
16  2.910383e-11  4.001777e-11  4.774847e-11      1.512795e-16  ...   
17  2.728484e-11  3.910827e-11  4.638423e-11      1.512795e-16  ...   
18  2.728484e-11  3.728928e-11  4.490630e-11      1.512795e-16  ...   
19  2.546585e-11  3.637979e-11  4.388312e-11      1.512795e-16  ...   
20  2.592060e-11  3.547029e-11  4.251888e-11      1.512795e-16  ...   
21  2.455636e-11  3.456080e-11  4.126832e-11      1.512795e-16  ...   
22  2.410161e-11  3.274181e-11  4.035883e-11      1.512795e-16  ...   
23  2

In [ ]:
final_prediction_df.sum(axis = 1)

0     276.415553
1     275.252001
2     274.092548
3     272.937188
4     271.785914
5     270.638720
6     269.495599
7     268.356543
8     267.221547
9     266.090604
10    264.963706
11    263.840846
12    262.722018
13    261.607214
14    260.496427
15    259.389649
16    258.286874
17    257.188094
18    256.093301
19    255.002488
20    253.915648
21    252.832772
22    251.753853
23    250.678883
24    249.607854
25    248.540759
26    247.477589
27    246.418336
28    245.362993
29    244.311552
dtype: float64

In [ ]:
weekly_df = death_by_state[death_by_state.columns[::7]]
weekly_df.head()

1/22/20  1/29/20  2/5/20  2/12/20  2/19/20  2/26/20  3/4/20  \
Province_State                                                                
Alabama               0        0       0        0        0        0       0   
Alaska                0        0       0        0        0        0       0   
American Samoa        0        0       0        0        0        0       0   
Arizona               0        0       0        0        0        0       0   
Arkansas              0        0       0        0        0        0       0   

                3/11/20  3/18/20  3/25/20  ...  9/28/22  10/5/22  10/12/22  \
Province_State                             ...                               
Alabama               0        0        1  ...    20395    20422     20473   
Alaska                0        0        1  ...     1364     1393      1393   
American Samoa        0        0        0  ...       34       34        34   
Arizona               0        0        6  ...    31370    31406     31455   
Arkansas              0        0        2  ...    12131    12235     12334   

                10/19/22  10/26/22  11/2/22  11/9/22  11/16/22  11/23/22  \
Province_State                                                             
Alabama            20505     20533    20558    20558     20617     20631   
Alaska              1393      1413     1413     1413      1436      1436   
American Samoa        34        34       34       34        34        34   
Arizona            31514     31548    31573    31613     31647     31709   
Arkansas           12396     12452    12506    12523     12528     12545   

                11/30/22  
Province_State            
Alabama            20652  
Alaska              1436  
American Samoa        34  
Arizona            31751  
Arkansas           12564  

[5 rows x 150 columns]

In [ ]:
weekly_final_prediction_df = pd.DataFrame()
for state in range(0,58):
  test = pd.DataFrame(weekly_df.iloc[state])
  current_state = test.columns[0]
  ##### WARNING: is the data already counting cumulative or is it daily cases?
  test.columns=['cum_death']
  test['new_death']=test['cum_death'].diff().fillna(test['cum_death'])
  initial_value = [0.027,0.03,500]
  bnds = [(0, None), (0, None), (0, None)]
  res = minimize(error,initial_value, args = (149,test.new_death), bounds = bnds, tol=1e-8, method = 'Powell')
  print(res.x)
  weekly_final_prediction_df[current_state] = prediction(res.x,147,4)

[2.53662352e-03 3.92312856e-02 2.17136281e+04]
[4.52641064e-04 5.09960391e-02 1.47285756e+03]
[3.57395004e-03 1.33183661e-02 4.48146283e+01]
[3.43372743e-03 3.05269579e-02 3.43702057e+04]
[2.66275774e-03 3.12050306e-02 1.38800931e+04]
[2.06263090e-04 1.21178910e-01 7.24063712e+04]
[3.20626451e-02 1.16183360e-10 5.27822425e+03]
[2.92646453e-02 2.81844403e+00 3.34078602e-05]
[3.12357184e-02 4.30241101e-09 7.90453323e+02]
[3.53125138e-09 5.56901951e-09 6.43449008e-09]
[9.41167042e-03 2.09157117e-01 8.70870944e+02]
[2.35516153e-03 3.26506380e-02 9.07310363e+04]
[2.85444702e-03 3.14652795e-02 4.47340466e+04]
[0.01051798 0.3051801  3.41965871]
[7.72908374e-06 3.20634994e+00 7.64195563e-02]
[6.46040022e-04 4.31410170e-02 1.86911744e+03]
[1.24122522e-03 4.18165501e-02 5.65449680e+03]
[5.46105007e-03 2.52364494e-02 4.25895024e+04]
[3.69622168e-03 2.76973013e-02 2.75777080e+04]
[3.72143107e-03 3.43623597e-02 1.04236208e+04]
[3.01691855e-03 3.31493823e-02 1.02760462e+04]
[1.23231917e-03 3.8553935

In [ ]:
weekly_final_prediction_df

Alabama    Alaska  American Samoa    Arizona   Arkansas  California  \
0  30.737555  4.084786        0.174536  70.778633  35.755428    0.097930   
1  29.559719  3.902083        0.172993  68.680416  34.739994    0.086736   
2  28.423980  3.726545        0.171447  66.636268  33.748125    0.076822   
3  27.329070  3.557984        0.169897  64.645307  32.779600    0.068041   

   Colorado  Connecticut  Delaware  Diamond Princess  ...  Tennessee  \
0  1.543645          0.0  0.254214      2.272181e-17  ...  98.522272   
1  1.494937          0.0  0.246396      2.272181e-17  ...  95.742944   
2  1.447766          0.0  0.238819      2.272181e-17  ...  93.023694   
3  1.402083          0.0  0.231474      2.272181e-17  ...  90.364377   

        Texas       Utah  Vermont  Virgin Islands   Virginia  Washington  \
0  130.273301  14.356599      0.0        0.219721  76.765895   67.110227   
1  125.396130  13.899406      0.0        0.216256  74.857779   65.568653   
2  120.689757  13.454407      0.0        0.212838  72.984703   64.047737   
3  116.149098  13.021437      0.0        0.209467  71.146721   62.548029   

   West Virginia  Wisconsin   Wyoming  
0      25.131085  48.393448  4.685878  
1      24.242326  47.152261  4.490882  
2      23.379393  45.935887  4.303139  
3      22.541964  44.744230  4.122453  

[4 rows x 58 columns]

In [ ]:
weekly_final_prediction_df.sum(axis=1)

0    1966.177380
1    1908.668365
2    1852.592750
3    1797.931651
dtype: float64

In [ ]:
monthly_df = death_by_state[death_by_state.columns[::30]]
monthly_df.head()

1/22/20  2/21/20  3/22/20  4/21/20  5/21/20  6/20/20  7/20/20  \
Province_State                                                                  
Alabama               0        0        0      183      529      838     1291   
Alaska                0        0        0        9       10       12       18   
American Samoa        0        0        0        0        0        0        0   
Arizona               0        0        2      208      764     1346     2784   
Arkansas              0        0        0       42      110      224      363   

                8/19/20  9/18/20  10/18/20  ...  2/10/22  3/12/22  4/11/22  \
Province_State                              ...                              
Alabama            1944     2428      2788  ...    17502    18832    19379   
Alaska               29       45        67  ...     1114     1201     1228   
American Samoa        0        0         0  ...        0        0       11   
Arizona            4634     5451      5827  ...    26856    28090    29681   
Arkansas            631     1173      1704  ...     9937    10892    11313   

                5/11/22  6/10/22  7/10/22  8/9/22  9/8/22  10/8/22  11/7/22  
Province_State                                                               
Alabama           19606    19692    19786   19974   20239    20473    20558  
Alaska             1268     1285     1285    1309    1338     1393     1413  
American Samoa       29       31       31      33      34       34       34  
Arizona           30230    30372    30572   30842   31162    31406    31573  
Arkansas          11410    11512    11608   11775   11951    12301    12521  

[5 rows x 35 columns]

In [ ]:
monthly_final_prediction_df = pd.DataFrame()
for state in range(0,58):
  test = pd.DataFrame(monthly_df.iloc[state])
  current_state = test.columns[0]
  ##### WARNING: is the data already counting cumulative or is it daily cases?
  test.columns=['cum_death']
  test['new_death']=test['cum_death'].diff().fillna(test['cum_death'])
  initial_value = [0.027,0.03,500]
  bnds = [(0, None), (0, None), (0, None)]
  res = minimize(error,initial_value, args = (34,test.new_death), bounds = bnds, tol=1e-8, method = 'Powell')
  print(res.x)
  monthly_final_prediction_df[current_state] = prediction(res.x,33,2)

[1.09724254e-02 1.66298404e-01 2.17996097e+04]
[ 0.02684564  1.71448828 14.37953792]
[1.19940817e-03 1.68337786e-01 7.01835424e+01]
[1.48915765e-02 1.27672369e-01 3.46636125e+04]
[1.14451831e-02 1.34034738e-01 1.38623322e+04]
[5.35237879e-02 1.04530323e+00 7.39875900e+03]
[1.20972417e-01 9.13257263e-10 6.07894933e+03]
[4.10707613e-02 1.01075066e+00 6.31964760e+03]
[1.34604120e-08 2.12809506e+01 1.14047808e+02]
[3.26854551e-09 4.30765061e-09 2.02775460e-19]
[1.07007376e-07 1.89569394e+01 1.02737586e+02]
[1.01454213e-02 1.39112837e-01 9.12009821e+04]
[1.22557219e-02 1.34034755e-01 4.48517831e+04]
[6.91080988e-05 5.25268658e-09 1.32095586e+03]
[6.12289269e-03 1.39868027e-01 4.77216164e+02]
[3.20142015e-03 1.74532836e-01 1.92992348e+03]
[5.46213323e-03 1.76437466e-01 5.69701164e+03]
[2.34913681e-02 1.07135084e-01 4.26821792e+04]
[1.58923368e-02 1.17443116e-01 2.76827646e+04]
[1.62962386e-02 1.45902717e-01 1.05235482e+04]
[1.30010451e-02 1.38932003e-01 1.03802358e+04]
[5.20900843e-03 1.6570

In [ ]:
monthly_final_prediction_df.sum(axis=1)

0    10065.541882
1     8916.678214
dtype: float64

In [ ]:
monthly_final_prediction_df.to_csv('monthly.csv')

In [ ]:
weekly_final_prediction_df.to_csv('weekly.csv')

In [ ]:
final_prediction_df.to_csv('daily.csv')